USE COSECHANDO;


INSERT INTO PROMOTORES(PROMOTOR_ID, NOMBRE_PR, DESCRIPCION_PR, NUMCONVENIO_PR) VALUES
('PROMO001','SAGARPA','SECRETARIA DE AGRICULTURA Y DESARROLLO RURAL','0000001'),
('PROMO002','DDRT','DISTRITO DE DESARROLLO RURAL DE TULANCINGO','0000002'),
('PROMO003','CADER','CENTRO DE APOYO AL DESARROLLO RURAL','0000003');

INSERT INTO MUNICIPIO(MUNICIPIO_ID, NOMBRE_M, ESTADO_M)VALUES
('MUNIC001', 'TULANCINGO DE BRAVO', 'HIDALGO'),
('MUNIC002', 'CUAUTEPEC DE HINOJOSA','HIDALGO'),
('MUNIC003', 'SANTIAGO TULANTEPEC DE LUGO GUERRERO', 'HIDALGO');

INSERT INTO NIVEL(NIVEL_ID, NOMBRE_N, DESCRIPCION_N) VALUES
('NIVEL001','INICIAL','NIVEL DE INICIO PARA LOS USUARIOS'),
('NIVEL002','PRINCIPIANTE','EL SEGUNDO NIVEL ALCANZADO POR UN USUARIO'),
('NIVEL003','INTERMEDIO','EL NIVEL MEDIO PARA CADA UNO DE LOS USUARIOS'),
('NIVEL004','AVANZADO 1', 'EL ULTIMO NIVEL DE UN USUARIO'),
('NIVEL005','AVANZADO 2', 'NIVEL OTORGADO A LOS USUARIOS MAS ANTIGUOS');

INSERT INTO TIPOUSUARIO(TIPOUSUARIO_ID,TIPO,DESCRIPCION) VALUES
('TUSER001','ADMINISTRADOR','USUARIO CAPAZ DE MODIFICAR ARTICULOS'),
('TUSER002','PROMOTOR','USUARIO CAPAZ DE PUBLICAR INFORMACION'),
('TUSER003','ORDINARIO','USUARIO PROMEDIO');
