CREATE DATABASE IF NOT EXISTS COSECHANDO;
USE COSECHANDO;

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE IF NOT EXISTS USUARIO(
USUARIO_ID	CHAR(8)	PRIMARY KEY,
NOMBRE_U	VARCHAR(50)	NOT NULL,
APELLIDO_U	VARCHAR(50)	NOT NULL,
CORREO_U	VARCHAR(70)	NOT NULL,
CUENTA_ACCESO_U	TINYINT	NOT NULL,
TIPO_USUARIO	TINYINT	NOT NULL,
NIVEL_ID	CHAR(8)	NOT NULL,
TIPOUSUARIO_ID CHAR(8)	NOT NULL
);

DROP TABLE IF EXISTS TERRENO;
CREATE TABLE IF NOT EXISTS TERRENO(
TERRENO_ID	CHAR(8)	PRIMARY KEY,
LATITUD_T	VARCHAR(50) NOT NULL,
LONGITUD_T	VARCHAR(50)	NOT NULL,
DIRECCION_T	VARCHAR(255)	NOT NULL,
TAMANIO_T	VARCHAR(20),
USUARIO_ID	CHAR(8),
REGION_ID	CHAR(8)
);

DROP TABLE IF EXISTS REGION;
CREATE TABLE IF NOT EXISTS REGION(
REGION_ID	CHAR(8)	PRIMARY KEY,
NOMBRE_RE	VARCHAR(50)	NOT NULL,
MUNICIPIO_ID	VARCHAR(50),
TIPOSUELO_ID	CHAR(8)
);

DROP TABLE IF EXISTS NIVEL;
CREATE TABLE IF NOT EXISTS NIVEL(
NIVEL_ID	CHAR(8)	PRIMARY KEY,
NOMBRE_N	VARCHAR(30)	NOT NULL,
DESCRIPCION	VARCHAR(100)
);

DROP TABLE IF EXISTS RECOMPENSA;
CREATE TABLE IF NOT EXISTS RECOMPENSA(
RECOMPENSA_ID	CHAR(8)	PRIMARY KEY,
RECOMPENSA_R	VARCHAR(30)	NOT NULL,
DESCRIPCION_R	VARCHAR(100)	NOT NULL,
PROMOTOR_ID	CHAR(8)
);

DROP TABLE IF EXISTS NIVEL_RECOMPENSA;
CREATE TABLE IF NOT EXISTS NIVEL_RECOMPENSA(
NIVEL_ID	CHAR(8),
RECOMPENSA_ID	CHAR(8)
);

DROP TABLE IF EXISTS REGION_PLANTA;
CREATE TABLE IF NOT EXISTS REGION_PLANTA(
REGION_ID	CHAR(8)	NOT NULL,
PLANTA_ID	CHAR(8)	NOT NULL
);

DROP TABLE IF EXISTS PLANTA;
CREATE TABLE IF NOT EXISTS PLANTA(
PLANTA_ID	CHAR(8)		PRIMARY KEY,
TAMAÑO_APROX_P	INT,
TIPO_P		VARCHAR(50)
);
