DROP DATABASE IF EXISTS COSECHANDO;
CREATE DATABASE IF NOT EXISTS COSECHANDO;
USE COSECHANDO;


DROP TABLE IF EXISTS USUARIO;
CREATE TABLE IF NOT EXISTS USUARIO(
USUARIO_ID	VARCHAR(8)	PRIMARY KEY,
NOMBRE_U	VARCHAR(50)	NOT NULL,
APELLIDO_U	VARCHAR(50)	NOT NULL,
CORREO_U	VARCHAR(70)	NOT NULL,
PASSWORD_U	VARCHAR(50) NOT NULL,
CUENTA_ACCESO_U	TINYINT,
NIVEL_ID	CHAR(8),
TIPOUSUARIO_ID CHAR(8)
);


DROP TABLE IF EXISTS TIPOUSUARIO;
CREATE TABLE IF NOT EXISTS TIPOUSUARIO(
TIPOUSUARIO_ID	CHAR(8)	PRIMARY KEY,
TIPO	VARCHAR(50)	NOT NULL,
DESCRIPCION	VARCHAR(100)
);


DROP TABLE IF EXISTS TERRENO;
CREATE TABLE IF NOT EXISTS TERRENO(
TERRENO_ID	CHAR(8)	PRIMARY KEY,
COORDENADAS	VARCHAR(50) NOT NULL,
TAMANIO_T	VARCHAR(20),
USUARIO_ID	CHAR(8),
REGION_ID	CHAR(8),
DIRECCION_ID CHAR(8)
);

DROP TABLE IF EXISTS DIRECCION;
CREATE TABLE DIRECCION(
DIRECCION_ID	CHAR(8) PRIMARY KEY,
CALLE	VARCHAR(30),
NUMERO	VARCHAR(6),
COLONIA	VARCHAR(30));

DROP TABLE IF EXISTS REGION;
CREATE TABLE IF NOT EXISTS REGION(
REGION_ID	CHAR(8)	PRIMARY KEY,
NOMBRE_RE	VARCHAR(50)	NOT NULL,
MUNICIPIO_ID	VARCHAR(50),
TIPOSUELO_ID	CHAR(8)
);


DROP TABLE IF EXISTS TIPOSUELO;
CREATE TABLE IF NOT EXISTS TIPOSUELO(
TIPOSUELO_ID	CHAR(8)	PRIMARY KEY,
NOMBRE	VARCHAR(100)	NOT NULL,
REGION_ID	CHAR(8)
);


DROP TABLE IF EXISTS NIVEL;
CREATE TABLE IF NOT EXISTS NIVEL(
NIVEL_ID	CHAR(8)	PRIMARY KEY,
NOMBRE_N	VARCHAR(30)	NOT NULL,
DESCRIPCION_N	VARCHAR(100)
);


DROP TABLE IF EXISTS RECOMPENSA;
CREATE TABLE IF NOT EXISTS RECOMPENSA(
RECOMPENSA_ID	CHAR(8)	PRIMARY KEY,
RECOMPENSA_R	VARCHAR(30)	NOT NULL,
DESCRIPCION_R	VARCHAR(100)	NOT NULL,
PROMOTOR_ID	CHAR(8)
);


DROP TABLE IF EXISTS NIVEL_RECOMPENSA;
CREATE TABLE IF NOT EXISTS NIVEL_RECOMPENSA(
NIVEL_ID	CHAR(8),
RECOMPENSA_ID	CHAR(8)
);


DROP TABLE IF EXISTS PLANTA;
CREATE TABLE IF NOT EXISTS PLANTA(
PLANTA_ID	CHAR(8)	PRIMARY KEY,
TAMANIOAPROX_P	VARCHAR(10),
TIPO	VARCHAR(50)	NOT NULL
);


DROP TABLE IF EXISTS CUIDADOS;
CREATE TABLE IF NOT EXISTS CUIDADOS(
CUIDADO_ID	CHAR(8)	PRIMARY KEY,
TIEMPOEJECUCION_CU	TIME,
FECHAAPLICACION_CU	DATE	NOT NULL,
RECURSOS_CU	VARCHAR(255)	NOT NULL
);


DROP TABLE IF EXISTS CUIDADOS_PLANTA;
CREATE TABLE IF NOT EXISTS CUIDADOS_PLANTA(
PLANTA_ID	CHAR(8),
CUIDADO_ID	CHAR(8)
);


DROP TABLE IF EXISTS REGIONPLANTA;
CREATE TABLE IF NOT EXISTS REGIONPLANTA(
REGION_ID	CHAR(8),
PLANTA_ID	CHAR(8)
);


DROP TABLE IF EXISTS MUNICIPIO;
CREATE TABLE IF NOT EXISTS MUNICIPIO(
MUNICIPIO_ID	CHAR(8)	PRIMARY KEY,
NOMBRE_M	VARCHAR(100)	NOT NULL,
ESTADO_M	VARCHAR(100)	NOT NULL
);


DROP TABLE IF EXISTS PROMOTORES;
CREATE TABLE IF NOT EXISTS PROMOTORES(
PROMOTOR_ID CHAR(8)	PRIMARY KEY,
NOMBRE_PR	VARCHAR(25)	NOT NULL,
DESCRIPCION_PR	VARCHAR(255),
NUMCONVENIO_PR	CHAR(7) NOT NULL
);


ALTER TABLE USUARIO ADD FOREIGN KEY (NIVEL_ID) REFERENCES NIVEL(NIVEL_ID);
ALTER TABLE USUARIO ADD FOREIGN KEY (TIPOUSUARIO_ID) REFERENCES TIPOUSUARIO(TIPOUSUARIO_ID);
ALTER TABLE TERRENO ADD FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID);
ALTER TABLE TERRENO ADD FOREIGN KEY (REGION_ID) REFERENCES REGION(REGION_ID);
ALTER TABLE TERRENO ADD FOREIGN KEY (DIRECCION_ID) REFERENCES DIRECCION(DIRECCION_ID);

INSERT INTO PROMOTORES(PROMOTOR_ID, NOMBRE_PR, DESCRIPCION_PR, NUMCONVENIO_PR) VALUES
('PROMO001','SAGARPA','SECRETARIA DE AGRICULTURA Y DESARROLLO RURAL','0000001'),
('PROMO002','DDRT','DISTRITO DE DESARROLLO RURAL DE TULANCINGO','0000002'),
('PROMO003','CADER','CENTRO DE APOYO AL DESARROLLO RURAL','0000003');

INSERT INTO MUNICIPIO(MUNICIPIO_ID, NOMBRE_M, ESTADO_M)VALUES
('MUNIC001', 'TULANCINGO DE BRAVO', 'HIDALGO'),
('MUNIC002', 'CUAUTEPEC DE HINOJOSA','HIDALGO'),
('MUNIC003', 'SANTIAGO TULANTEPEC DE LUGO GUERRERO', 'HIDALGO');

INSERT INTO NIVEL(NIVEL_ID, NOMBRE_N, DESCRIPCION_N) VALUES
('NIVEL001','INICIAL','NIVEL DE INICIO PARA LOS USUARIOS'),
('NIVEL002','PRINCIPIANTE','EL SEGUNDO NIVEL ALCANZADO POR UN USUARIO'),
('NIVEL003','INTERMEDIO','EL NIVEL MEDIO PARA CADA UNO DE LOS USUARIOS'),
('NIVEL004','AVANZADO 1', 'EL ULTIMO NIVEL DE UN USUARIO'),
('NIVEL005','AVANZADO 2', 'NIVEL OTORGADO A LOS USUARIOS MAS ANTIGUOS');

INSERT INTO TIPOUSUARIO(TIPOUSUARIO_ID,TIPO,DESCRIPCION) VALUES
('TUSER001','ADMINISTRADOR','USUARIO CAPAZ DE MODIFICAR ARTICULOS'),
('TUSER002','PROMOTOR','USUARIO CAPAZ DE PUBLICAR INFORMACION'),
('TUSER003','ORDINARIO','USUARIO PROMEDIO');
SELECT * FROM TIPOUSUARIO;
drop trigger IF EXISTS PRIMERO;
DELIMITER //
CREATE TRIGGER PRIMERO AFTER INSERT
ON USUARIO
FOR EACH ROW 
BEGIN
SET @YUKO = (SELECT USUARIO_ID FROM USUARIO ORDER BY USUARIO_ID DESC LIMIT 1);
SET @LUZU = (SELECT TIPOUSUARIO_ID FROM USUARIO WHERE USUARIO_ID = @YUKO);
SET @TUSER = (SELECT TIPO FROM TIPOUSUARIO WHERE TIPOUSUARIO_ID = 'TUSER001');
IF @LUZU = NULL THEN BEGIN
	INSERT INTO USUARIO(TIPOUSUARIO_ID) VALUE (@TUSER);
END; END IF;

END//
DELIMITER ;

DROP PROCEDURE IF EXISTS IO_K_C;

DELIMITER //
CREATE PROCEDURE IO_K_C(
	IN PRO_NOMBRE_U	VARCHAR(50),
    IN PRO_APELLIDO_U	VARCHAR(50),
    IN PRO_CORREO_U	VARCHAR(70),
    IN PRO_PASSWORD_U VARCHAR(50))
    BEGIN
    
		SET @CONTADOR = (SELECT COUNT(*) FROM USUARIO);
		SET @YUKO = (SELECT(CONCAT('USER',@CONTADOR)));
		INSERT INTO USUARIO(USUARIO_ID,NOMBRE_U,APELLIDO_U,CORREO_U,PASSWORD_U) 
        VALUES (@YUKO,PRO_NOMBRE_U,PRO_APELLIDO_U,PRO_CORREO_U,PRO_PASSWORD_U);    
        
    END //
DELIMITER ;

SELECT * FROM USUARIO;

CALL IO_K_C('DANIELA','RUBIALES','DANIELA@GMAIL.COM','ESTA_ES_MI_PASSWORD');

SELECT * FROM USUARIO;


