USE COSECHANDO;

/*
drop trigger IF EXISTS PRIMERO;
DELIMITER //
CREATE TRIGGER PRIMERO AFTER INSERT
ON USUARIO
FOR EACH ROW 
BEGIN
SET @YUKO = (SELECT USUARIO_ID FROM USUARIO ORDER BY USUARIO_ID DESC LIMIT 1);
SET @LUZU = (SELECT TIPOUSUARIO_ID FROM USUARIO WHERE USUARIO_ID = @YUKO);
SET @TUSER = (SELECT TIPO FROM TIPOUSUARIO WHERE TIPOUSUARIO_ID = 'TUSER001');
IF @LUZU = NULL THEN BEGIN
	INSERT INTO USUARIO(TIPOUSUARIO_ID) VALUE (@TUSER);
END; END IF;

END//
DELIMITER ;
*/
